# Site settings
title: 經濟時事與多媒體出版
description: 課程及活動內容
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: <h1>經濟時事與多媒體出版</h1>
footername: 國立臺北大學 <span class="love">❤</span> 經濟學系
user_description: 彈性課程 x 實作導向
user_title: 課程及活動內容
email: mtlin@gm.ntpu.edu.tw
twitter_username:
github_username:  tpemartin/Multimedia-Publication-of-Economic-Issues
gplus_username:
facebook_pagename: groups/675099912682029/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
